// <auto-generated />
using System;
using CvShortlist.SelfHosted.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvShortlist.SelfHosted.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.CandidateCv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Analysis")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobOpeningId")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobOpeningId", "Rating")
                        .IsDescending(false, true);

                    b.HasIndex("JobOpeningId", "Sha256FileHash");

                    b.HasIndex("JobOpeningId", "DateCreated", "FileName")
                        .IsDescending(false, true, false);

                    b.ToTable("CandidateCvs");
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.CandidateCvBlob", b =>
                {
                    b.Property<Guid>("CandidateCvId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("CandidateCvId");

                    b.ToTable("CandidateCvBlobs");
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.JobOpening", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalysisLanguage")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasFilter("Status = 1");

                    b.ToTable("JobOpenings");
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.CandidateCv", b =>
                {
                    b.HasOne("CvShortlist.SelfHosted.Models.JobOpening", "JobOpening")
                        .WithMany("CandidateCvs")
                        .HasForeignKey("JobOpeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOpening");
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.CandidateCvBlob", b =>
                {
                    b.HasOne("CvShortlist.SelfHosted.Models.CandidateCv", null)
                        .WithOne("CandidateCvBlob")
                        .HasForeignKey("CvShortlist.SelfHosted.Models.CandidateCvBlob", "CandidateCvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.CandidateCv", b =>
                {
                    b.Navigation("CandidateCvBlob")
                        .IsRequired();
                });

            modelBuilder.Entity("CvShortlist.SelfHosted.Models.JobOpening", b =>
                {
                    b.Navigation("CandidateCvs");
                });
#pragma warning restore 612, 618
        }
    }
}
